# C/C++ with GCC

# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  - main

pr:
  - main

strategy:
  matrix:
#    linux:
#      imageName: 'ubuntu-latest'
#      extraBuildArguments: ''
#      extraConfigureArguments: '-DBUILD_EXAMPLES=True'
#      conanInstallCommand: 'pip install conan==1.61.0'
#      conanDefineDefaultProfile: 'conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default'
#      extraInstallArguments: '-o build_examples=True'
    mac:
      imageName: 'macOS-latest'
      extraBuildArguments: ''
      extraConfigureArguments: ''
      conanInstallCommand: 'python3 -m ensurepip && pip3 install conan==1.61.0'
      conanDefineDefaultProfile: 'conan profile new default --detect'
      extraInstallArguments: ''
#    windows:
#      imageName: 'windows-latest'
#      extraBuildArguments: '--config Release'
#      extraConfigureArguments: ''
#      conanInstallCommand: 'pip install conan==1.61.0'
#      conanDefineDefaultProfile: 'conan profile new default --detect'
#      extraInstallArguments: ''
  
pool:
    vmImage: $(imageName)

steps:
  - script: |
      $(conanInstallCommand)
      $(conanDefineDefaultProfile)
      conan profile show default     
    displayName: Install Conan
  - script: |
      mkdir build
      cd build
      conan install -s build_type=Release -o build_testing=True $(extraInstallArguments) --build missing ..
    workingDirectory: '.'
    displayName: Conan Install Dependencies
  - task: CMake@1
    displayName: CMake Configure
    inputs:
      cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=True $(extraConfigureArguments)'
      workingDirectory: 'build'
  - task: CMake@1
    displayName: CMake Build
    inputs:
      cmakeArgs: '--build . $(extraBuildArguments)'
      workingDirectory: 'build'
  - task: Bash@3
    displayName: Test
    inputs:
      targetType: 'inline'
      script: |
        ctest --output-junit testResult.xml --rerun-failed --output-on-failure
      workingDirectory: 'build/tests'
  - task: PublishTestResults@2
    condition: always()
    displayName: Publish Test Results
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'build/tests/testResult.xml'
  - task: ArtifactoryConan@1
    displayName: Create Conan Package
    inputs:
      conanCommand: 'Create'
      createPath: '.'
      createReference: 'seboste/test'      
